# Generated by Django 2.2.15 on 2020-09-05 10:26

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='файл изображения')),
                ('description', models.TextField(verbose_name='Комментарий к изображению')),
                ('created', models.DateField(auto_now_add=True, db_index=True, verbose_name='Время создания объекта в БД')),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
            ],
        ),
    ]
