# Generated by Django 2.2.15 on 2020-09-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UploadImage',
        ),
    ]
