# Generated by Django 2.2.15 on 2020-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200905_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='coordinates',
            field=models.CharField(max_length=200, null=True, verbose_name='Геоданные снимка'),
        ),
    ]
