# Generated by Django 2.2.15 on 2020-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_uploadimage_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='social_activity',
            field=models.CharField(max_length=50, null=True, verbose_name='Количество людей на фотографии'),
        ),
    ]
