# Generated by Django 2.2.15 on 2020-09-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200905_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='social_activity',
        ),
    ]
